  documentation:
  - changed-files:
    - any-glob-to-any-file: "architecture-decision-record/**"
    - any-glob-to-any-file: "diagrams/**"
    - any-glob-to-any-file: "documentation/**"
    - any-glob-to-any-file: "README.md"
    - any-glob-to-any-file: "source/**"