apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-efs-claim
  namespace: grafana
spec:
  volumeName: grafana-efs-pv
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
