---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: aws-efs-csi-driver
  name: aws-efs-csi-driver
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.eks_cluster.efs_csi_driver_iam_role_arn }}
