apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-expandable
  annotations:
    meta.helm.sh/release-name: shared-resources
    meta.helm.sh/release-namespace: kube-system
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    app.kubernetes.io/managed-by: Helm
provisioner: ebs.csi.aws.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3

