apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dummy-prometheus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Release.Namespace }}.{{ .Values.host}}
    http:
      paths:
      - path: /prometheus
        pathType: Prefix
        backend:
          service:
            name: dummy-prometheus
            port:
              number: 80
