apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingressNamePlaceholder }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.hostPlaceholder }}
    http:
      paths:
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.ServiceNamePlaceholder }}
            port:
              number: {{ .Values.PortNumberPlaceholder }}

