environment: ""
production_account_id: ""
pre_production_account_id: ""
development_account_id: ""
dhcpApiBasicAuthUsername: ""
dhcpApiBasicAuthPassword: ""
cloudwatch_iam_role: ""
cloudwatchExporterDevelopmentArn: ""
cloudwatchExporterPreProductionArn: ""
alertmanager:
  smtp:
    from: ""
    username: ""
    password: ""
  alert_rules:
    ima_slack_webhook_url: ""
    network_access_control_pre_production_slack_webhook_url: ""
    development_pre_production_dhcp_dns_slack_webhook_url: ""
