apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-query-grafana-datasource
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://thanos-query.monitoring.svc.cluster.local:9090/
      access: proxy
      isDefault: true
      jsonData:
        timeInterval: 30s
      version: 1
      editable: false
