apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: Helm
    release: {{ .Release.Name }}
    alertmanagerConfig: alertmanager-config
  name: primary-alertmanagerconfig
  namespace: {{ .Release.Namespace }}
spec:
  route:
    receiver: Master Route
    groupBy:
    - 'service'
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 24h
    routes:
      - receiver: NVVS DevOps Critical
        groupWait: 10s
        repeatInterval: 24h
        matchers:
          - name: service
            value: DNS DHCP
          - name: severity
            value: critical
      - receiver: NVVS DevOps
        groupWait: 10s
        repeatInterval: 24h
        matchers:
          - name: service
            value: DNS DHCP
          - name: severity
            value: warning
      - receiver: NVVS DevOps Dev PreProd Critical
        groupWait: 10s
        repeatInterval: 24h
        matchers:
          - name: service
            value: DNS DHCP Dev PreProd
          - name: severity
            value: critical
      - receiver: NVVS DevOps Dev PreProd
        groupWait: 10s
        repeatInterval: 24h
        matchers:
          - name: service
            value: DNS DHCP Dev PreProd
          - name: severity
            value: warning
      - receiver: Team PKI
        groupWait: 10s
        repeatInterval: 7d
        matchers:
          - name: service
            value: certificate-services
      - receiver: Team IGS
        groupWait: 10s
        repeatInterval: 24h
        matchers:
          - name: service
            value: Internet Gateway Service
      - receiver: Team Sec Logging
        groupWait: 10s
        repeatInterval: 24h
        matchers:
          - name: service
            value: Security Logging
      - receiver: Network Access Control Pre-Production
        groupWait: 10s
        repeatInterval: 24h
        matchers:
          - name: service
            value: Network Access Control Pre-Production
      - receiver: Network Access Control Production
        groupWait: 10s
        repeatInterval: 24h
        matchers:
          - name: service
            value: Network Access Control
          - name: severity
            value: warning
      - receiver: Network Access Control Critical
        groupWait: 10s
        repeatInterval: 24h
        matchers:
          - name: service
            value: Network Access Control
          - name: severity
            value: critical
      - receiver: Team Mercury Production
        groupWait: 10s
        repeatInterval: 24h
        matchers:
          - name: service
            value: Mercury Production
      - receiver: mojnetworks-alerts
        groupWait: 10s
        repeatInterval: 7d
        matchers:
          - name: service
            value: NACS Certificate Expiry Warning
          - name: severity
            value: warning
      - receiver: NVVS DevOps Critical
        groupWait: 10s
        repeatInterval: 7d
        matchers:
          - name: service
            value: SMTP Relay
          - name: severity
            value: critical

  receivers:
    - name: Master Route
      slackConfigs:
        - apiURL:
            key: ima_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#mojo-ima-platform-alerts-dev-preprod'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.icon_emoji" . }}'`}}
    - name: NVVS DevOps Dev PreProd Critical
      slackConfigs:
        - apiURL:
            key: development_pre_production_dhcp_dns_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#mojo-staff-device-dhcp-dns-alerts-dev-preprod'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.icon_emoji" . }}'`}}
    - name: NVVS DevOps Dev PreProd
      slackConfigs:
        - apiURL:
            key: development_pre_production_dhcp_dns_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#mojo-staff-device-dhcp-dns-alerts-dev-preprod'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.icon_emoji" . }}'`}}
    - name: NVVS DevOps
      slackConfigs:
        - apiURL:
            key: dhcp_dns_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#mojo-staff-device-dhcp-dns-alerts'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.icon_emoji" . }}'`}}
    - name: NVVS DevOps Critical
      slackConfigs:
        - apiURL:
            key: dhcp_dns_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#mojo-staff-device-dhcp-dns-alerts'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.icon_emoji" . }}'`}}
      pagerdutyConfigs:
        - routingKey:
            key: pagerduty_routing_key
            name: slack-webhooks
      emailConfigs:
        - to: 'InfrastructureAutomationTeam@justice.gov.uk'
        - to: 'mojnoc@justice.gov.uk'
        - to: 'mojnoc_alerts@justice.gov.uk'
    - name: Team PKI
      slackConfigs:
        - apiURL:
            key: certificate_services_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#mojo-staff-certificate-services-alerts'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.icon_emoji" . }}'`}}
    - name: Team IGS
      slackConfigs:
        - apiURL:
            key: networks_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#mojo-network-alerts'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.icon_emoji" . }}'`}}
    - name: Team Sec Logging
      slackConfigs:
        - apiURL:
            key: ost_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#mojo-staff-device-logging-infrastructure-alerts'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.icon_emoji" . }}'`}}
    - name: Network Access Control Pre-Production
      slackConfigs:
        - apiURL:
            key: network_access_control_pre_production_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#network-access-control-alerts-dev-pre-prod'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.icon_emoji" . }}'`}}
    - name: Network Access Control Production
      slackConfigs:
        - apiURL:
            key: network_access_control_production_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#network-access-control-alerts'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.icon_emoji" . }}'`}}
    - name: Network Access Control Critical
      slackConfigs:
        - apiURL:
            key: network_access_control_critical_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#network-access-control-critical-alerts'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.icon_emoji" . }}'`}}
      pagerdutyConfigs:
        - routingKey:
            key: pagerduty_routing_key
            name: slack-webhooks
            optional: false
      emailConfigs:
        - to: 'InfrastructureAutomationTeam@justice.gov.uk'
        - to: 'mojnoc@justice.gov.uk'
        - to: 'mojnoc_alerts@justice.gov.uk'
    - name: Team Mercury Production
      emailConfigs:
        - to: 'techops-3ls-euc@justice.gov.uk'
    - name: mojnetworks-alerts
      emailConfigs:
        - to: 'e8y8j3c1v0d2l4b8@mojdt.slack.com'
