apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: Helm
    release: {{ .Release.Name }}
    alertmanagerConfig: alertmanager-config
  name: primary-alertmanagerconfig
  namespace: {{ .Release.Namespace }}
spec:
  route:
    receiver: CNS Team - Slack
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 24h
    groupBy:
      - 'service'
    routes:
      - receiver: CNS Team - Slack
        group_wait: 10s
        repeat_interval: 24h
        matchers:
          - name: service
            value: IMA
          - name: severity
            value: critical
      - receiver: CNS Team - Pagerduty
        group_wait: 10s
        repeat_interval: 24h
        matchers:
          - name: service
            value: DNS DHCP
          - name: service
            value: SMTP Relay
      - receiver: Team PKI
        group_wait: 10s
        repeat_interval: 7d
        matchers:
          - name: service
            value: certificate-services
      - receiver: Team IGS
        group_wait: 10s
        repeat_interval: 24h
        matchers:
          - name: service
            value: Internet Gateway Service
      - receiver: Team Sec Logging
        group_wait: 10s
        repeat_interval: 24h
        matchers:
          - name: service
            value: Security Logging
      - receiver: Network Access Control Pre-Production
        group_wait: 10s
        repeat_interval: 24h
        matchers:
          - name: service
            value: Network Access Control Pre-Production
      - receiver: Network Access Control Production
        group_wait: 10s
        repeat_interval: 24h
        matchers:
          - name: service
            value: Network Access Control
          - name: severity
            value: warning
      - receiver: Network Access Control Critical
        group_wait: 10s
        repeat_interval: 24h
        matchers:
          - name: service
            value: Network Access Control
          - name: severity
            value: critical
      - receiver: Team Mercury Production
        group_wait: 10s
        repeat_interval: 24h
        matchers:
          - name: service
            value: Mercury Production

  receivers:
    - name: CNS Team - Slack
      slackConfigs:
        - apiURL:
            key: ima_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#mojo-ima-platform-alerts-dev-preprod'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.iconEmoji" . }}'`}}
    - name: CNS Team - Pagerduty
      pagerdutyConfigs:
        - serviceKey:
            key: pagerduty_service_key
            name: alertmanager-secrets
            optional: false
    - name: Team PKI
      slackConfigs:
        - apiURL:
            key: certificate_services_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#mojo-staff-infrastructure-certificate-services-alerts'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.iconEmoji" . }}'`}}
    - name: Team IGS
      slackConfigs:
        - apiURL:
            key: networks_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#mojo-network-alerts'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.iconEmoji" . }}'`}}
    - name: Team Sec Logging
      slackConfigs:
        - apiURL:
            key: ost_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#mojo-staff-device-logging-infrastructure-alerts'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.iconEmoji" . }}'`}}
    - name: Network Access Control Pre-Production
      slackConfigs:
        - apiURL:
            key: network_access_control_pre_production_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#network-access-control-alerts-dev-pre-prod'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.iconEmoji" . }}'`}}
    - name: Network Access Control Production
      slackConfigs:
        - apiURL:
            key: network_access_control_production_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#network-access-control-alerts'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.iconEmoji" . }}'`}}
    - name: Network Access Control Critical
      slackConfigs:
        - apiURL:
            key: network_access_control_critical_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#network-access-control-critical-alerts'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.iconEmoji" . }}'`}}
    - name: Team Mercury Production
      emailConfigs:
        - to: 'techops-3ls-euc@justice.gov.uk'
