apiVersion: v1
kind: Secret
metadata:
  name: aws-account-ids
  namespace: grafana
type: Opaque
data:
  DEV_AWS_ACCOUNT_ID: MDY4MDg0MDMwNzU0
  PREP_AWS_ACCOUNT_ID: NDczNjMwMzYwNzI3
  PROD_AWS_ACCOUNT_ID: MDM3MTYxODQyMjUy