kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: blackbox-protective-dns-probe
  namespace: monitoring
spec:
  prober:
    url: prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  jobName: "protective_dns_probe"
  module: protective_dns_probe
  targets:
    staticConfig:
      static:
        - 25.26.27.28
        - 25.25.25.25
      relabelingConfigs:
        - sourceLabels: [__address__]
          targetLabel: __param_target
        - sourceLabels: [__param_target]
          targetLabel: instance
        - targetLabel: __address__
          replacement: "prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115"
