kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: blackbox-http
  namespace: monitoring
spec:
  prober:
    url: prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  jobName: "blackbox-http"
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://dhcp-dns-admin.staff.service.justice.gov.uk
        - https://dhcp-dns-admin.dev.staff.service.justice.gov.uk
        - https://dhcp-dns-admin.prep.staff.service.justice.gov.uk
        - https://monitoring-alerting.staff.service.justice.gov.uk
        - https://monitoring-alerting.dev.staff.service.justice.gov.uk
        - https://monitoring-alerting.prep.staff.service.justice.gov.uk
        - https://enrolment.certificates.prep.staff.service.justice.gov.uk/csrscep/a0361_user/pkiclient.exe?operation=GetCACaps
        - https://enrolment.certificates.staff.service.justice.gov.uk/csrscep/b0361_user/pkiclient.exe?operation=GetCACaps
        - https://portal.vpn.justice.gov.uk
        - https://portal.prep.vpn.justice.gov.uk
        - https://alpha-fw.vpn.justice.gov.uk
        - https://sop.govsharedservices.gov.uk:4450
        - https://gateway-c.internal.vpn.justice.gov.uk
        - https://gateway-f.internal.vpn.justice.gov.uk
