apiVersion: v1
kind: Service
metadata:
  name: prometheus-blackbox-exporter
spec:
  selector:
    app: blackbox-exporter
  ports:
    - name: http
      protocol: TCP
      port: 9115
      targetPort: 9115
