apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: monitoring
    prometheus-operator-validated: "true"
  creationTimestamp: "2022-08-25T09:36:30Z"
  generation: 1
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: Helm
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}.certificate-services.rules
  namespace: {{ .Release.Namespace }}
spec:
  groups:
  - name: certificate-services.rules
    rules:
    - alert: A SSL Certificate is Expiring
      expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
      for: 10m
      labels:
        severity: warning
        service: certificate-services
      annotations:
        summary: "SSL certificate will expire soon on (instance {{ "{{ $labels.instance }}" }})"
        description: "The SSL certificate expires in {{ "{{ $value | humanizeDuration }}" }}"
        grafana_dashboard_url: https://monitoring-alerting.staff.service.justice.gov.uk/d/r8eWoHpGz/proto-certificate-monitor?orgId=1
        
