{
 "title": "Home",
 "tags": [ "provisioned" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Welcome",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "<h1>NVVS DevOps Monitoring 🕵️‍♂️</h1>\n\n\n<p>The <a href=\"https://github.com/ministryofjustice/nvvs-devops-monitor#nvvs-devops-monitor\" target=\"_blank\"> NVVS DevOps Monitoring</a> and Alerting Platform is best described in the linked repository.\n\n<p></p>\n\n<h3>Provisioning Dashboards 📊</h3>\n\nPreviously changes to Monitoring had to be merged as code to the monitoring repository, this is no longer the case as the new solution uses persistent storage to store dashboards. \n\nDashboards can be provisioned as code, if required. If you would like to do this please get in touch. \n\n<p></p>\n\n<h3>Remote Write ✍</h3>\nTo consume metrics from other Prometheus instances using the remote write functionality, configure your prometheus to remote write to the URL:\n\n<a href=\"https://thanos-receive.monitoring-alerting.staff.service.justice.gov.uk/api/v1/receive\"> https://thanos-receive.monitoring-alerting.staff.service.justice.gov.uk/api/v1/receive</a>\n\n<p></p>\n\n<h3>Contact Us 🤔</h3>\n\nIf you have any questions please contact us on the <a href=\"https://mojdt.slack.com/archives/C026AFE617T\"> #ask-nvvs-devops</a> Slack channel."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"})-1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pending Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NACS Alerts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{service=\"Network Access Control\"})",
     "filters": "service=~\"IMAP\"",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS DHCP Alerts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{service=\"DNS DHCP\"})",
     "filters": "service=~\"DNS DHCP\"",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certificate Services",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{service=\"certificate-services\"})",
     "filters": "service=~\"Network\"",
     "legendFormat": "__auto",
     "receiver": "service=certificate-services"
    }
   ]
  },
  {
   "title": "Popular Dashboards",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 11 },
   "options": {
    "content": "- [DNS & DHCP Status](https://monitoring-alerting.staff.service.justice.gov.uk/d/E8-yWIqMk/dns-dhcp-status?orgId=1&refresh=5m)\r\n- [KEA DHCP Metrics](https://monitoring-alerting.staff.service.justice.gov.uk/d/cEwjsH1Gk/kea-dhcp-metrics?orgId=1&refresh=1m)\r\n- [Certificate Monitor](https://monitoring-alerting.staff.service.justice.gov.uk/d/r8eWoHpGz/proto-certificate-monitor?orgId=1)\r\n- [Network Access Control](https://monitoring-alerting.staff.service.justice.gov.uk/d/CFhQiFxnk/network-access-control?orgId=1)\r\n- [SMTP Relay](https://monitoring-alerting.staff.service.justice.gov.uk/d/h36Havfik/postfix-smtp-relay?orgId=1)"
   },
   "targets": [
    {
     "expression": "fields @timestamp, RunningTaskCount\n| filter (Type=\"Service\")\n| filter (ServiceName=\"mojo-production-ima-prom-ecs-service\")\n| sort @timestamp desc\n| limit 1",
     "logGroupNames": [
      "/aws/ecs/containerinsights/mojo-production-ima-ecs-cluster/performance"
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "External Health Status 🩺",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 11 },
   "options": {
    "content": "| [Amazon Web Services UK](https://status.aws.amazon.com/#EU_block) | [Azure Services UK](https://status.azure.com/en-gb/status)  |\n|---|---|\n| [GitHub](https://www.githubstatus.com/) | [Slack](https://status.slack.com/) | \n"
   }
  }
 ]
}