{
 "title": "DNS DHCP Status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 0 },
   "options": {
    "content": "# DNS DHCP Service Overview\n\nThis dashboard gives a quick glance at DNS DHCP as a whole.\nThe DNS and DHCP sections confirm the containers are running in AWS and are supplimented by an example metric. You can review the architecture diagram of DNS DHCP at the bottom of this page.\n---\n\n---\n\nLook for the ![image](https://i.ibb.co/zbf99Js/link.png) in the corner of each panel to drill down in more detail.\n         "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Admin Portal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 5 },
   "options": {
    "content": "## Admin Portal\n\nAll DNS DHCP changes are made through the Admin portal.  \n\nYou can access the portal directly from the panel on the right.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "DNS DHCP Admin Portal",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"https://dhcp-dns-admin.staff.service.justice.gov.uk\"}"
    }
   ]
  },
  {
   "title": "DHCP (AWS Fargate)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DHCP Primary",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aws_ecs_containerinsights_running_task_count_average{dimension_ServiceName=\"staff-device-production-dhcp-primary-service\"}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DHCP Standby",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aws_ecs_containerinsights_running_task_count_average{dimension_ServiceName=\"staff-device-production-dhcp-standby-service\"}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DHCP API",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aws_ecs_containerinsights_running_task_count_average{dimension_ServiceName=\"staff-device-production-dhcp-api-service\"}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lease Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_kea_dhcp_alloc_engine_v4_alloc_error_sum"
    },
    {
     "expr": "aws_kea_dhcp_alloc_engine_v4_alloc_fail_sum"
    },
    {
     "expr": "aws_kea_dhcp_alloc_engine_v4_alloc_fail_classes_sum"
    }
   ]
  },
  {
   "title": "DNS  (AWS Fargate)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DNS Primary",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aws_ecs_containerinsights_running_task_count_average{dimension_ServiceName=\"staff-device-production-dns-service\"}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DNS Requests in the last 24 Hours",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 5, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_dns_bind_server_qry_success_average"
    }
   ]
  },
  {
   "title": "Architecture",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Diagram",
     "type": "text",
     "gridPos": { "h": 17, "w": 22, "x": 0, "y": 23 },
     "options": {
      "content": "![image](https://github.com/ministryofjustice/staff-device-dns-dhcp-infrastructure/blob/main/diagrams/pttp-dns-dhcp-infra.png?raw=true)"
     }
    }
   ]
  }
 ]
}