apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-webhooks
  namespace: monitoring
data:
  ima_slack_webhook_url: {{ .Values.alertmanager.alert_rules.ima_slack_webhook_url }}
  certificate_services_slack_webhook_url: {{ .Values.alertmanager.alert_rules.certificate_services_slack_webhook_url }}
  networks_slack_webhook_url: {{ .Values.alertmanager.alert_rules.networks_slack_webhook_url }}
  ost_slack_webhook_url: {{ .Values.alertmanager.alert_rules.ost_slack_webhook_url }}
  network_access_control_production_slack_webhook_url: {{ .Values.alertmanager.alert_rules.network_access_control_production_slack_webhook_url }}
  network_access_control_pre_production_slack_webhook_url: {{ .Values.alertmanager.alert_rules.network_access_control_pre_production_slack_webhook_url }}
  network_access_control_critical_slack_webhook_url: {{ .Values.alertmanager.alert_rules.network_access_control_critical_slack_webhook_url }}
  pagerduty_routing_key: {{ .Values.alertmanager.alert_rules.pagerduty_routing_key }}
