apiVersion: v1
data:
  ima_slack_webhook_url: aHR0cHM6Ly9zbGFja3dlYmhvb2suY29tCg==
  certificate_services_slack_webhook_url: aHR0cHM6Ly9zbGFja3dlYmhvb2suY29tCg==
  networks_slack_webhook_url: aHR0cHM6Ly9zbGFja3dlYmhvb2suY29tCg==
  ost_slack_webhook_url: aHR0cHM6Ly9zbGFja3dlYmhvb2suY29tCg==
  network_access_control_production_slack_webhook_url: aHR0cHM6Ly9zbGFja3dlYmhvb2suY29tCg==
  network_access_control_pre_production_slack_webhook_url: aHR0cHM6Ly9zbGFja3dlYmhvb2suY29tCg==
  network_access_control_critical_slack_webhook_url: aHR0cHM6Ly9zbGFja3dlYmhvb2suY29tCg==
kind: Secret
metadata:
  name: slack-webhooks
  namespace: monitoring
type: Opaque
