{
 "title": "Postfix SMTP Relay",
 "description": "Prometheus Postfix exporter metrics.",
 "tags": [ "SMTP-Relay" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(postfix_up,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cumulative Emails Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "postfix_smtpd_messages_processed_total{instance=~\"$instance\",job=\"postfix\"}"
    }
   ]
  },
  {
   "title": "Emails Processed Per Load Balancer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "postfix_smtpd_messages_processed_total{instance=~\"$instance\",job=\"postfix\"}"
    }
   ]
  },
  {
   "title": "Rate of change in deferred status count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(postfix_smtp_status_deferred{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "cleanup(8)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Message processing rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(postfix_cleanup_messages_processed_total{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Rejection ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(postfix_cleanup_messages_rejected_total{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "qmgr(8)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Message insertion rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(postfix_qmgr_messages_inserted_size_bytes_count{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Message insertion bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(postfix_qmgr_messages_inserted_size_bytes_sum{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Message removal rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(postfix_qmgr_messages_removed_total{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "showq(8)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of enqueued messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "postfix_showq_message_size_bytes_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Size of enqueued messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "postfix_showq_message_size_bytes_sum{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Average age of enqueued messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(postfix_showq_message_age_seconds_count{instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  {
   "title": "smtp(8)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Message processing rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(postfix_smtp_delivery_delay_seconds_count{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Average delivery duration by stage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(postfix_smtp_delivery_delay_seconds_sum{instance=~\"$instance\"}[5m])) by (stage)) / (sum(rate(postfix_smtp_delivery_delay_seconds_count{instance=~\"$instance\"}[5m])) by (stage))"
    }
   ]
  },
  {
   "title": "TLS connection ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(postfix_smtp_tls_connections_total{instance=~\"\"}[5m])) by (instance) / (sum(rate(postfix_smtp_delivery_delay_seconds_count{instance=~\"$instance\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TLS protocol/cipher usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(postfix_smtp_tls_connections_total[5m])"
    }
   ]
  },
  {
   "title": "smtpd(8)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connect rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(postfix_smtpd_connects_total{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Disconnect rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(postfix_smtpd_disconnects_total{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Connections lost",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(postfix_smtpd_connections_lost_total{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "SASL authentication failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(postfix_smtpd_sasl_authentication_failures_total{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Forward-confirmed reverse DNS erros",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(postfix_smtpd_forward_confirmed_reverse_dns_errors_total{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Message processing rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(postfix_smtpd_messages_processed_total{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Rejection ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(postfix_smtpd_messages_rejected_total{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "TLS connection ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(postfix_smtpd_tls_connections_total{instance=~\"$instance\"}[5m])) by (instance) / (sum(rate(postfix_smtpd_connects_total{instance=~\"$instance\"}[5m])) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TLS protocol/cipher usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(postfix_smtpd_tls_connections_total[5m])"
    }
   ]
  }
 ]
}