apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: monitoring
    prometheus-operator-validated: "true"
  creationTimestamp: "2022-08-25T09:36:30Z"
  generation: 1
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: Helm
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}.smtp-relay.rules
  namespace: {{ .Release.Namespace }}
spec:
  groups:
  - name: smtp-relay.rules
    rules:
      - alert: SMTP ECS High CPU/Memory Alert
        expr: aws_ecs_cpuutilization_average{dimension_ClusterName="staff-infrastructure-production-smtp-relay-cluster"} > 60 or aws_ecs_memory_utilization_average{dimension_ClusterName="staff-infrastructure-production-smtp-relay-cluster"} > 60
        for: 5m
        labels:
          severity: critical
          service: SMTP Relay
        annotations:
          summary: SMTP Relay CPU or MemoryUtilization is above 60 percent
          description: The Memory or CPU is currently {{ "{{ $value }}" }}
          grafana_dashboard_url: https://monitoring-alerting.staff.service.justice.gov.uk/d/h36Havfik/postfix
      - alert: SMTP ECS Task Count
        expr: aws_ecs_containerinsights_running_task_count_average{dimension_ClusterName="staff-infrastructure-production-smtp-relay-cluster"} < 1
        for: 5m
        labels:
          severity: critical
          service: SMTP Relay
        annotations:
          summary: SMTP Relay ECS Task count is below 1
          description: The ECS task count has fallen below 1 for SMTP.
          grafana_dashboard_url: https://monitoring-alerting.staff.service.justice.gov.uk/d/h36Havfik/postfix
      - alert: SMTP Rejection Ratio
        expr: rate(postfix_cleanup_messages_rejected_total{instance=~"$instance"}[5m]) > 0
        for: 1m
        labels:
          severity: critical
          service: SMTP Relay
        annotations:
          summary: SMTP Rejection ratio is above 0.
          description: The SMTP rejection ratio has increased above 0.
          grafana_dashboard_url: https://monitoring-alerting.staff.service.justice.gov.uk/d/h36Havfik/postfix
      - alert: SMTP Deferred Status Count
        expr: rate(postfix_smtp_status_deferred{instance=~"$instance"}[5m]) > 0.0200
        for: 5m
        labels:
          severity: critical
          service: SMTP Relay
        annotations:
          summary: SMTP Rate of change in deferred status count is above 0.0200
          description: The SMTP deferred rate of change has increased above 0.0200
          grafana_dashboard_url: https://monitoring-alerting.staff.service.justice.gov.uk/d/h36Havfik/postfix
