{
 "title": "DHCP Lease Statistics",
 "tags": [
  "DHCP",
  "Kea"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "SiteName", "label": "MoJO Site Name", "query": { "query": "MoJO_site_info" } },
   { "name": "customSubnet", "label": "Find Site by Subnet", "query": "10.80.39.0/24" },
   {
    "name": "SiteName2",
    "query": {
     "query": "MoJO_site_info{Info=~\".+$customSubnet.+\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Subnets for $SiteName",
   "type": "table",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "MoJO_site_info{Info=~\".+$SiteName.+\"} ",
     "legendFormat": "{{SiteName}}"
    }
   ]
  },
  {
   "title": "Site Finder ($customSubnet)",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "options": { "content": "# $SiteName2" },
   "targets": [
    { "legendFormat": "{{SiteName}}" }
   ]
  },
  {
   "title": "Subnet Usage for $customSubnet",
   "type": "stat",
   "description": "Paste a subnet into the \"Find Site by Subnet\" box to see it's usage here!",
   "gridPos": { "h": 3, "w": 7, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subnet_statistics_usage{cidr_block=\"$customSubnet\"}",
     "legendFormat": "Leases"
    }
   ]
  },
  {
   "title": "Total Number of leases across MoJO",
   "type": "stat",
   "gridPos": { "h": 13, "w": 10, "x": 13, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(subnet_statistics_leases)", "legendFormat": "Leases" }
   ]
  },
  {
   "title": "Subnet Usage by CIDR > 60%",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "subnet_statistics_usage > 60", "legendFormat": "{{cidr_block}}" }
   ]
  }
 ]
}