{
 "title": "KEA DHCP Metrics",
 "tags": [
  "Kea",
  "DHCP"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "account_id",
    "label": "Environment",
    "query": "\"$PROD_AWS_ACCOUNT_ID\",\"$PREP_AWS_ACCOUNT_ID\",\"$DEV_AWS_ACCOUNT_ID\""
   }
  ]
 },
 "panels": [
  {
   "title": "AWS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DHCP ECS Task count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_ecs_containerinsights_running_task_count_average{dimension_ClusterName=~\".+dhcp.+\",account_id=\"$account_id\"}",
     "legendFormat": "{{dimension_ServiceName}}"
    }
   ]
  },
  {
   "title": "NLB UnHealthyHostCount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_networkelb_un_healthy_host_count_average{dimension_TargetGroup=~\".+dhcp.+\",account_id=\"$account_id\"}",
     "legendFormat": "{{dimension_AvailabilityZone}} - {{dimension_LoadBalancer}}"
    }
   ]
  },
  {
   "title": "RDS IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aws_rds_read_iops_average{account_id=\"$account_id\"})"
    },
    {
     "expr": "sum(aws_rds_write_iops_average{account_id=\"$account_id\"})"
    }
   ]
  },
  {
   "title": "NLB ProcessBytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_networkelb_processed_bytes_average{dimension_LoadBalancer=~\".+dhcp.+\",account_id=\"$account_id\"}",
     "legendFormat": "{{dimension_LoadBalancer}}"
    }
   ]
  },
  {
   "title": "RDS CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average{dimension_DBInstanceIdentifier=~\".+dhcp.+\",account_id=\"$account_id\"}",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "ECS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "staff-device-production-dhcp-cluster"
     },
     "expr": "aws_ecs_cpuutilization_average{dimension_ClusterName=~\".+dhcp.+\",account_id=\"$account_id\"}",
     "legendFormat": "{{dimension_ClusterName}}",
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "staff-device-production-dhcp-cluster"
     },
     "expr": "aws_ecs_memory_utilization_average{dimension_ClusterName=~\".+dhcp.+\",account_id=\"$account_id\"}",
     "legendFormat": "{{dimension_ClusterName}}",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Custom Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "KEA Server",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_kea_dhcp_error_sum{account_id=\"$account_id\"}",
     "legendFormat": "Primary Error"
    },
    {
     "expr": "aws_kea_dhcp_fatal_sum{account_id=\"$account_id\"}",
     "legendFormat": "Primary Fatal Error"
    },
    {
     "expr": "aws_kea_dhcp_warn_sum{account_id=\"$account_id\"}",
     "legendFormat": "Primary Warning"
    },
    {
     "expr": "aws_kea_dhcp_standby_error_sum{account_id=\"$account_id\"}",
     "legendFormat": "Standby Error"
    },
    {
     "expr": "aws_kea_dhcp_standby_fatal_sum{account_id=\"$account_id\"}",
     "legendFormat": "Standby Fatal"
    },
    {
     "expr": "aws_kea_dhcp_standby_warn_sum{account_id=\"$account_id\"}",
     "legendFormat": "Standby Warning"
    }
   ]
  },
  {
   "title": "KEA Configuration",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_kea_dhcp_configuration_successful_sum{account_id=\"$account_id\"}",
     "legendFormat": "Primary - Successful"
    },
    {
     "expr": "aws_kea_dhcp_config_reload_failed_sum{account_id=\"$account_id\"}",
     "legendFormat": "Primary - Reload Failed"
    },
    {
     "expr": "aws_kea_dhcp_standby_configuration_successful_sum{account_id=\"$account_id\"}",
     "legendFormat": "Standby - Successful"
    },
    {
     "expr": "aws_kea_dhcp_standby_config_reload_failed_sum{account_id=\"$account_id\"}",
     "legendFormat": "Standby - Reload Failed"
    }
   ]
  },
  {
   "title": "KEA HA",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_kea_dhcp_ha_sync_failed_sum{account_id=\"$account_id\"}",
     "legendFormat": "Primary - HA Sync Failed"
    },
    {
     "expr": "aws_kea_dhcp_ha_heartbeat_communications_failed_sum{account_id=\"$account_id\"}",
     "legendFormat": "Primary - HA Heartbeat Communication Failed"
    },
    {
     "expr": "aws_kea_dhcp_standby_ha_sync_failed_sum{account_id=\"$account_id\"}",
     "legendFormat": "Standby - HA Sync Failed"
    },
    {
     "expr": "aws_kea_dhcp_standby_ha_heartbeat_communications_failed_sum{account_id=\"$account_id\"}",
     "legendFormat": "Standby - HA Heartbeat Communication Failed"
    }
   ]
  },
  {
   "title": "KEA Failed Leases",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_kea_dhcp_alloc_engine_v4_alloc_error_sum{account_id=\"$account_id\"}",
     "legendFormat": "Primary  - Allocation Error"
    },
    {
     "expr": "aws_kea_dhcp_alloc_engine_v4_alloc_fail_sum{account_id=\"$account_id\"}",
     "legendFormat": "Primary  - Allocation Fail"
    },
    {
     "expr": "aws_kea_dhcp_alloc_engine_v4_alloc_fail_classes_sum{account_id=\"$account_id\"}",
     "legendFormat": "Primary  - Allocation Fail Classes"
    },
    {
     "expr": "aws_kea_dhcp_standby_alloc_engine_v4_alloc_error_sum{account_id=\"$account_id\"}",
     "legendFormat": "Standby - Allocation Error"
    },
    {
     "expr": "aws_kea_dhcp_standby_alloc_engine_v4_alloc_fail_sum{account_id=\"$account_id\"}",
     "legendFormat": "Standby  - Allocation Fail"
    },
    {
     "expr": "aws_kea_dhcp_standby_alloc_engine_v4_alloc_fail_classes_sum{account_id=\"$account_id\"}",
     "legendFormat": "Standby - Allocation Fail Classes"
    }
   ]
  },
  {
   "title": "Rate of Discover",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aws_kea_dhcp_pkt4_discover_received_average{account_id=\"$account_id\"}[15m])",
     "legendFormat": "Primary"
    }
   ]
  },
  {
   "title": "Rate of Offer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aws_kea_dhcp_pkt4_nak_sent_average{account_id=\"$account_id\"}[15m])",
     "legendFormat": "Primary"
    }
   ]
  },
  {
   "title": "Rate of Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aws_kea_dhcp_pkt4_request_received_average{account_id=\"$account_id\"}[15m])  ",
     "legendFormat": "Primary"
    }
   ]
  },
  {
   "title": "Rate of Acknowledge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aws_kea_dhcp_pkt4_ack_sent_average{account_id=\"$account_id\"}[15m])",
     "legendFormat": "Primary"
    }
   ]
  },
  {
   "title": "NAK",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_kea_dhcp_pkt4_nak_sent_average{account_id=\"$account_id\"}",
     "legendFormat": "Primary - pkt4-nak-sent"
    },
    {
     "expr": "aws_kea_dhcp_pkt4_nak_received_average{account_id=\"$account_id\"}",
     "legendFormat": "Primary - pkt4-nak-received"
    }
   ]
  },
  {
   "title": "Pkt4 Decline Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_kea_dhcp_pkt4_decline_received_average{account_id=\"$account_id\"}",
     "legendFormat": "Primary - Decline Received"
    }
   ]
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DHCP Server recent logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expression": "fields @timestamp, @message | sort @timestamp desc | limit 250",
     "logGroupNames": [
      "staff-device-production-dhcp-server-log-group"
     ],
     "queryMode": "Logs",
     "region": "eu-west-2"
    }
   ]
  },
  {
   "title": "DHCP Server Error Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expression": "FIELDS @message\n| filter @message like /ERROR/",
     "logGroupNames": [
      "staff-device-production-dhcp-server-log-group"
     ],
     "queryMode": "Logs",
     "region": "eu-west-2"
    }
   ]
  }
 ]
}