image:
  repository: 602401143452.dkr.ecr.eu-west-2.amazonaws.com/amazon/aws-load-balancer-controller
serviceAccount:
  create: false
  name: aws-load-balancer-controller
serviceMonitor:
  enabled: true
resources:
  limits:
    cpu: 30m
    memory: 64Mi
  requests:
    cpu: 15m
    memory: 32Mi
