query:
  stores:
    - "dnssrv+_grpc._tcp.kube-prometheus-stack-thanos-discovery.monitoring.svc.cluster.local"
  resources:
    limits:
      memory: "800Mi"
      ephemeral-storage: "1Gi"
      cpu: "300m"
    requests:
      memory: "600Mi"
      ephemeral-storage: "50Mi"
      cpu: "200m"
queryFrontend:
  enabled: false
storegateway:
  enabled: true
  resources:
    limits:
      memory: "2Gi"
    requests:
      memory: "1Gi"
compactor:
  enabled: true
  resources:
    limits:
      cpu: 600m
    requests:
      cpu: 500m
receive:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true
