replicas: 2
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'provisioned'
      orgId: 1
      folder: 'Provisioned'
      type: file
      disableDeletion: true
      editable: false
      options:
        path: /var/lib/grafana/dashboards/provisioned
    - name: 'DNS DHCP'
      orgId: 1
      folder: 'DNS DHCP'
      type: file
      disableDeletion: true
      editable: false
      options:
        path: /var/lib/grafana/dashboards/dns-dhcp
    - name: 'SMTP'
      orgId: 1
      folder: 'SMTP'
      type: file
      disableDeletion: true
      editable: false
      options:
        path: /var/lib/grafana/dashboards/smtp
    - name: 'NACS'
      orgId: 1
      folder: 'Network Access Control'
      type: file
      disableDeletion: true
      editable: false
      options:
        path: /var/lib/grafana/dashboards/nacs
sidecar:
  skipTlsVerify: true
  datasources:
    enabled: true
    searchNamespace: ALL
  dashboards:
    enabled: true
    SCProvider: false
    label: grafana_dashboards
    searchNamespace: ALL
    folder: /var/lib/grafana/dashboards
grafana.ini:
  analytics:
    check_for_updates: true
  log:
    mode: console
  dashboards:
    default_home_dashboard_path: /tmp/dashboards/default-grafana-dashboard.json
  auth.azuread:
    name: "Azure AD"
    enabled: true
    allow_sign_up: true
  plugins:
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  ingressClassName: nginx
persistence:
  enabled: true
  storageClassName: "efs-sc"
  size: 5Gi
  existingClaim: "grafana-efs-claim"
  accessModes:
    - ReadWriteMany
serviceMonitor:
  enabled: true
