kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
grafana:
  enabled: false
  forceDeployDatasources: true
  forceDeployDashboards: true
prometheus:
      prometheusSpec:
        podMonitorNamespaceSelector: {}
        podMonitorSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        ruleNamespaceSelector: {}
        ruleSelector: {}
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorNamespaceSelector: {}
        serviceMonitorSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
