serviceAccount:
  name: external-dns
txtPrefix: mojo-ima-ext-dns-
policy: sync
serviceMonitor:
  enabled: true
resources:
  limits:
    cpu: 20m
    memory: 64Mi
  requests:
    cpu: 10m
    memory: 32Mi
