replicas: 2
sidecar:
  datasources:
    enabled: true
    searchNamespace: ALL
  dashboards:
    enabled: true
    searchNamespace: ALL
    provider:
      folder: "Provisioned"
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  ingressClassName: nginx
persistence:
  enabled: true
  storageClassName: "efs-sc"
  size: 5Gi
  existingClaim: "grafana-efs-claim"
  accessModes:
    - ReadWriteMany
