kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
grafana:
  enabled: false
  forceDeployDatasources: false
  forceDeployDashboards: true
prometheus:
  prometheusSpec:
    podMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    ruleNamespaceSelector: {}
    ruleSelector: {}
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    thanos:
      objectStorageConfig:
        key: "objstore.yml"
        name: "thanos-objstore-secret"
  thanosService:
    enabled: true
  thanosServiceMonitor:
    enabled: true
