kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
grafana:
  enabled: false
  forceDeployDatasources: false
  forceDeployDashboards: true
  defaultDashboardsTimezone: "Europe/London"
prometheus:
  prometheusSpec:
    podMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    ruleNamespaceSelector: {}
    ruleSelector: {}
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs:
    - job_name: dhcp_portal_api
      scrape_interval: 120s
      scrape_timeout: 65s
      metrics_path: /probe
      params:
        module: [default]
      static_configs:
        - targets:
          - https://dhcp-dns-admin.dev.staff.service.justice.gov.uk/api/dhcp-stats
          - https://dhcp-dns-admin.prep.staff.service.justice.gov.uk/api/dhcp-stats
          - https://dhcp-dns-admin.staff.service.justice.gov.uk/api/dhcp-stats
      relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'prometheus-json-exporter.monitoring.svc.cluster.local:7979'
    - job_name: json_exporter
      metrics_path: /metrics
      honor_labels: true
      static_configs:
      - targets:
        - prometheus-json-exporter.monitoring.svc.cluster.local:7979
    - job_name: cloudwatch
      honor_labels: true
      static_configs:
      - targets:
        - cloudwatch-exporter:5000
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 8Gi
    thanos:
      objectStorageConfig:
        key: "objstore.yml"
        name: "thanos-objstore-secret"
  thanosService:
    enabled: true
  thanosServiceMonitor:
    enabled: true
