name: Deployment

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "montoring-impovements"

permissions:
  id-token: write
  contents: read

jobs:

  deploy-development:
    uses: ./.github/workflows/deployment_reusable_workflow.yml
    with:
      ENV: development
    secrets: inherit

  deploy-pre-production:
    needs: [deploy-development]
    uses: ./.github/workflows/deployment_reusable_workflow.yml
    with:
      ENV: pre-production
    secrets: inherit

  deploy-production:
    needs: [deploy-development, deploy-pre-production]
    uses: ./.github/workflows/deployment_reusable_workflow.yml
    with:
      ENV: production
    secrets: inherit
