name: Deployment

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

permissions:
  id-token: write
  contents: read

jobs:

  deploy-development:
    uses: ./.github/workflows/deployment_reusable_workflow.yml
    with:
      ENV: development
      ENABLED: ${{ github.development.enabled }}
    secrets: inherit

#  deploy-pre-production:
#    needs: [deploy-development]
#    uses: ./.github/workflows/deployment_reusable_workflow.yml
#    with:
#      ENV: pre-production
#      ENABLED: ${{ github.pre-production.enabled }}
#    secrets: inherit

#  destroy-development:
#    needs: [ deploy-development, deploy-pre-production]
#    uses: ./.github/workflows/deployment_reusable_workflow.yml
#    with:
#      ENV: development
#      ENABLED: false
#    secrets: inherit

  deploy-production:
    needs: [deploy-development, deploy-pre-production]
    uses: ./.github/workflows/deployment_reusable_workflow.yml
    with:
      ENV: production
      ENABLED: true
    secrets: inherit

#  destroy-pre-production:
#    needs: [ deploy-development, deploy-pre-production, deploy-production]
#    uses: ./.github/workflows/deployment_reusable_workflow.yml
#    with:
#      ENV: pre-production
#      ENABLED: false
#    secrets: inherit
