name: code-formatter

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-super-linter.yml@main
        with:
            super-linter-variables: |
              {
                VALIDATE_X: false
              }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
